name: Build and Push Docker Image to ECR
on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      
jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: latest # ${{ github.sha }}c
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          cd ./server
          echo "${{ secrets.ENV_PROD_CONTENT }}" > .env.prod
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

          # SSH into EC2 and run Docker commands
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} << EOF
            # Get Docker login command from ECR and execute it
            docker login -u AWS -p $(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) $ECR_REGISTRY

            # Pull the latest image
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            # # (Optional) Stop the current container
            docker rm -f $(docker ps -aq)

            # # Run the new container
            docker run -p 80:3000 --name programming-blog $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          EOF

          # Cleanup deploy key
          rm -f deploy_key.pem
